### ISSUE TITLE
Cannot scale or move graph

### ISSUE THREAD

**Issue by rremigius** [vasturiano/three-forcegraph#18]
Hi there, nice work on this graph visualization. I'm trying to get it to work with an existing THREE Scene containing other objects and a camera, but the graph is really large compared to my camera point-of-view (and I should not change the camera).

I would like to do something like this:

```javascript
var myGraph = new ThreeForceGraph()
    .graphData(myData);

myGraph.scale.set(0.1, 0.1, 0.1);

var myScene = new THREE.Scene();
myScene.add(myGraph);
```

However, even setting the scale to 0.5 disconnects the links from the nodes, like this:
![Screenshot from 2019-05-01 20-36-13](https://user-images.githubusercontent.com/1083451/57034818-d3e9a900-6c50-11e9-8cee-95efea862854.png)

It gets worse with smaller scale or larger position.

The same happens if I try to set the position of the graph object.

I also tried wrapping it in another Object3D:

```javascript
var wrapper = new Object3D();
wrapper.add(myGraph);
wrapper.scale.set(0.1, 0.1, 0.1);
myScene.add(wrapper);
```

but unfortunately this gives the same results.

Finally, I tried changing the node sizes, link sizes, link forces, etc etc, but I cannot manage to get the right results.

Is there a proper way to scale the graph as a whole, or is a current limitation?

Any help would be much appreciated!

**Comment by vasturiano** [comment]
Thanks for this report @rremigius. Took me a good bit of time to figure this one out.
As it turns out, the method [lookAt](https://threejs.org/docs/#api/en/core/Object3D.lookAt) (which was being used to orientate the cylinder links in the right direction) needs the coordinates translated from `world` to `local` if the parent scaling is not uniform, as in your case. Otherwise the object orientation is off, which is what was happening. The links weren't shorter, they were just pointing in the wrong direction.

If you pull the latest version (`1.17.3`) the issue should be fixed. Let me know if you hit any other snags.

Also, either method that you mentioned (with or without the wrapper) should work for scaling the object.
