### ISSUE TITLE
Node radius is not properly calculated

### ISSUE THREAD

**Issue by RaulPROP** [vasturiano/three-forcegraph#26]
I just realized that [the radius of the node is calculated as the cube root of the volume](https://github.com/vasturiano/three-forcegraph/blob/d02d90c5b489497a08b9f91cc33a96325a35cf46/src/forcegraph-kapsule.js#L676), but it should be calculated as the cube root of (3 times the volume divided by 4 times pi) (`Math.cbrt((3 * state.nodeRelSize) / (4 * Math.PI))`)

Is this a mistake or is this intended?

**Comment by vasturiano** [comment]
@RaulPROP thanks for reaching out. It's a good question.
Basically the `3/(4*pi)` is merely a scaling factor, due to the associative property of exponent operations. Essentially `cbrt(a*b) = cbrt(a)*cbrt(b)`.

In the case of this module the scaling constant is determined by the `nodeRelSize` property. That's what determines the conversion between the two independent units, from the node values onto the actual size on the three scene. Therefore there's no need to further apply a specific factor like the `3/(4*pi)`, which is more applicable when the two units are compatible to begin with, for example if we're calculating volume in cubic meters from radius in meters.

Hope that makes sense. :)

**Comment by RaulPROP** [comment]
Got it, thanks :)
