### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by tscgist** [vasturiano/three-forcegraph#4]
First, I want to give you positive feedback. Your work is very valuable. 
Please allow me a question. Is it possible to assign arrow heads to the links of a graph? If it is possible, could you post a small example. I have seen that the arrow helper is available, but frozen. 
Best regards 
Tom Schaefer

**Comment by vasturiano** [comment]
Thanks for reaching out @tscgist.

Currently, the way that is available to represent directionality is using particles that move in the direction of the link. Here's and example of what it looks like:
https://vasturiano.github.io/3d-force-graph/example/directional-links/
Here's the [example code](https://github.com/vasturiano/3d-force-graph/blob/master/example/directional-links/index.html) (it's using the [3d-force-graph](https://github.com/vasturiano/3d-force-graph) wrapper module, but the interface is the same on three-forcegraph).

I've chosen that method because it's easier to see the direction than an arrow head which just stands at the edge of the links and may be easy to miss, specially in a 3D setting where it's potentially hidden behind other objects.

But I'm willing to consider adding the feature in as an alternative method if there's useful cases that would profit from it. So, let me know your experience with it and if you'd still prefer the arrow heads.

**Comment by vasturiano** [comment]
@tscgist just letting you know that the graph now supports directional arrows (in addition to the moving particles mentioned above):
https://vasturiano.github.io/3d-force-graph/example/directional-links-arrows/

You can enable it using `.linkDirectionalArrowLength(<num>)`.
