### ISSUE TITLE
Interacting with nodes

### ISSUE THREAD

**Issue by dpan7** [vasturiano/three-forcegraph#8]
Hi there again,

Is there any "easy way" to interact with the graph nodes like in this example?

[https://github.com/vasturiano/3d-force-graph/blob/master/example/click-to-focus/index.html](url)

Functions such as **onNodeHover** and **onNodeClick** are not included in this npm package

My goal is to have something like a hover text tooltip on each Mesh and later on an interaction when someone clicks on a node.

I found a work around for the **onNodeHover** by adding ` document.addEventListener("mousemove")`, but I was wondering if there is more elegant solution from the API perspective.

Although I am able to retrieve the node (as 3D object presented as follows) when hovering, my actual data (__data field) presented as 

```
uuid: "999D36DF-CB74-4860-9577-D414845BC8F3"
castShadow: false
...
.__data : { 
color: "#1f78b4",
description: "Quadtree 1"
group: 2
id: "id4"
index: 3
name :"name4" 
val:1}
...
```
inside the object and I cannot find a way to retrieve, let say the name for example.

Do you have any insights?

Thank you in advance for your help.

**UPDATE:** 
`object['__data'].name `  did the trick, but I just wondering if there is more elegant solution.

**Comment by vasturiano** [comment]
@dpan7 `three-forcegraph` is just the nodes/links layout translated to a ThreeJS Object3D. It doesn't include any interaction mechanism and/or renderer/camera functionality. That's by design so that it's compatible with any kind of renderer, controller etc.

If you need a higher-level WebGL packaged renderer, there's always [3d-force-graph](https://github.com/vasturiano/3d-force-graph).

And yes, `object.__data` is the way to retrieve the object that is associated with a ThreeJS node/link object.

**Comment by dpan7** [comment]
Ok, thank you for the clarification.
